swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/profile/{accountId}/transactions:     
    get:  
      security : 
        - Bearer: [] 
      tags:
        - Transaction
      summary: Retrieve all transactions for the current month and grouped by account
      description: API to retrive transactions grouped by account for the current month.
      parameters :
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: The ID of the account
          required: true
          type: string
      produces:
        - application/json
      responses :
        '200':
          description: Transaction grouped by account for the current month were successfully retrieved.
          schema:
            $ref: '#/definitions/ListOfTransactionsResponse'
        '400':
          description: The field is invalid.
          schema:
            $ref: '#/definitions/InvalidFieldAccountId'
        '401':
          description: The request lacks valid authentication credentials. Check the "Authorization" header.
          schema:
            $ref: '#/definitions/ErrorAuthorized'
        '404':
          description: The requested resource was not found.
          schema:
            $ref: '#/definitions/ErrorNotFound'
  /user/profile/{accountId}/transactions/{transactionId}:
    get: 
      security: 
        - Bearer: []
      tags:
        - Transaction
      summary: View the details of a single transaction
      description: API for fetching the detail of transaction by its Id
      parameters :
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: The ID of the account
          required: true
          type: string          
        - in: path
          name: transactionId
          description: The ID of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses :
        '200':
          description: The transaction details were successfully retrieved.
          schema:
              $ref: '#/definitions/TransactionDetails'
        '400':
          description: The field is invalid.
          schema:
            $ref: '#/definitions/InvalidFieldAccountTransactionId'
        '401':
          description: The request lacks valid authentication credentials. Check the "Authorization" header.
          schema:
              $ref: '#/definitions/ErrorAuthorized'
        '404':
          description: The requested resource was not found.
          schema:
              $ref: '#/definitions/ErrorNotFound'
    put:
      security: 
        - Bearer: []
      tags:
        - Transaction
      summary: Update category on a transaction
      description: API for editing category on trasaction by its ID
      parameters :
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: The ID of the account
          required: true
          type: string          
        - in: path
          name: transactionId
          description: The ID of the transaction
          required: true
          type: string          
        - in: body
          name: body
          description: Update the transaction payload
          required: true
          schema:
              $ref: '#/definitions/UpdateTransactionCategory'
      produces :
        - application/json
      responses :
        '200':
          description: The category was successfully updated.
          schema:
            $ref: '#/definitions/UpdateTransCategoryResponse'
        '400':
          description: The field is invalid.
          schema:
            $ref: '#/definitions/InvalidFieldAccountTransactionId'
        '401':
          description: The request lacks valid authentication credentials. Check the "Authorization" header.
          schema:
              $ref: '#/definitions/ErrorAuthorized'
        '404':
          description: The requested resource was not found.
          schema:
              $ref: '#/definitions/ErrorNotFound'
  /user/profile/{accountId}/transactions/{transactionId}/notes :      
    post:
      security: 
        - Bearer: []
      tags:
        - Transaction
      summary: Add a new note to a transition
      description: API for adding a new note
      parameters :
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: The ID of the account
          required: true
          type: string 
        - in: path
          name: transactionId
          description: The ID of the transaction
          required: true
          type: string
        - in: body
          name: body
          description: add the transaction payload
          required: true
          schema: 
            $ref: '#/definitions/AddTransactionNote'
      produces:
        - application/json
      responses :
        '201':
          description: New note was successfully added.
          schema:
              $ref: '#/definitions/AddtransactionNoteResponse'
        '400':
          description: The field is invalid.
          schema:
              $ref: '#/definitions/InvalidFieldAccountTransactionId'
        '401':
          description: The request lacks valid authentication credentials. Check the "Authorization" header.
          schema:
              $ref: '#/definitions/ErrorAuthorized'
        '404':
          description: The requested resource was not found.
          schema:
              $ref: '#/definitions/ErrorNotFound'
  /user/profile/{accountId}/transactions/{transactionId}/notes/{noteId}:
    put:
      security: 
        - Bearer: []
      tags:
        - Transaction
      summary: Update note on a transaction
      description: API for editing note on trasaction by its ID
      parameters :
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: The ID of the account
          required: true
          type: string 
        - in: path
          name: transactionId
          description: The ID of the transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: The ID of the transaction note to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Update the transaction payload
          required: true
          schema:
              $ref: '#/definitions/UpdateTransactionNote'
      produces :
        - application/json
      responses :
        '200':
          description: The note was successfully updated.
          schema:
            $ref: '#/definitions/UpdateTransNoteResponse'
        '400':
          description: The field is invalid.
          schema:
            $ref: '#/definitions/InvalidFieldFull'
        '401':
          description: The request lacks valid authentication credentials. Check the "Authorization" header.
          schema:
              $ref: '#/definitions/ErrorAuthorized'
        '404':
          description: The requested resource was not found.
          schema:
              $ref: '#/definitions/ErrorNotFound'
    delete:
      security: 
        - Bearer: []
      tags:
        - Transaction
      summary: Delete note on a transaction
      description: API for removing note on transaction by its ID 
      parameters :
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: The ID of the account
          required: true
          type: string
        - in: path
          name: transactionId
          description: The ID of the transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: The ID of the transaction note to be deleted
          required: true
          type: string
      produces :
        - application/json
      responses :
        '204':
          description: The note on the transaction was successfully deleted
        '400':
          description: The field is invalid.
          schema:
              $ref: '#/definitions/InvalidFieldFull'
        '401':
          description: The request lacks valid authentication credentials. Check the "Authorization" header.
          schema:
              $ref: '#/definitions/ErrorAuthorized'
        '404':
          description: The requested resource was not found.
          schema:
              $ref: '#/definitions/ErrorNotFound'
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ListOfTransactionsResponse:
    type: object
    properties:
      accountId:
        type: integer
        example: 'a1234'
      transactions:
        type: array
        items:
          type: object
          properties:
            transactionId:
              type: integer
              example: 'b4578'
            date:
              type: string
              format: date
            amount:
              type: number
              format: double
              example: 308.58
            balance:
              type: number
              format: double
              example: 1408.01
            description:
              type: string
  TransactionDetails:
    type: object
    properties:
      transactionId:
        type: integer
        example: 'b4578'
      date:
        type: string
        format : date
      description:
        type: string
        description: transaction detail description ('Golden Sun Bakery')
      amount: 
        type: number
        format: double
        description: transaction amount in USD
        example: 75.78
      balance:
        type: number
        format: double
        description: transaction balance in USD
        example: 1500.12 
      type: 
        type: string
        description: transaction type
      category:
        type: string
        example: Food
      note:
        type: object
        description: transaction note
        properties:
          noteId:
            type: string
          content: 
            type: string
  AddTransactionNote:
    type: object
    properties:
      note:
        type: object
        properties:
          content: 
            type: string
  AddtransactionNoteResponse:
    type: object
    properties:
      status:
        type: string
        example: "success"
      message:  
        type: string
        example: "note added successfully"
      noteId:
        type: integer
        example: 'ab123'
      cerateAt: 
        type: string
        format: date
  UpdateTransCategoryResponse:
    type: object
    properties:
      status:
        type: string
        example: "success"
      message:  
        type: string
        example: "category updated successfully"
      updatedAt:
        type: string
        format: date
  UpdateTransNoteResponse:
    type: object
    properties:
      status:
        type: string
        example: "success"
      message:  
        type: string
        example: "note updated successfully"
      updatedAt:
        type: string
        format: date
  UpdateTransactionCategory: 
    type: object
    properties :
      category :
        type: string
        enum: 
          - "Food"
          - "Transportation"
          - "Healthcare"
          - "Entertainment"
          - "Other"
  UpdateTransactionNote :
    type: object
    properties :
      note:
        type: object
        properties:
          content: 
            type: string
  InvalidFieldAccountId: 
    type: object
    properties:
      status: 
        type: string
        example: "400"
      errorMessage:
        type: string
        example: "the field 'accountId' is invalid"
  InvalidFieldAccountTransactionId: 
    type: object
    properties:
      status: 
        type: string
        example: "400"
      errorMessage:
        type: string
        example: "the field 'accountId' or 'transactionId' is invalid"
  InvalidFieldFull: 
    type: object
    properties:
      status: 
        type: string
        example: "400"
      errorMessage:
        type: string
        example: "the field 'accountId' or 'transactionId' or 'noteId' is invalid"
  ErrorAuthorized:
    type: object
    properties:
      status:
        type: string
        example: "401"
      message:  
        type: string
        example: "Invalid authorization credentials"
      user_message:
        type: string
        example: "The session has expired or is invalid"
  ErrorNotFound : 
    type: object
    properties:
        status: 
          type: string
          example: "404"
        message:  
          type: string
          example: "the requested resource was not found"
  